# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rlinf.envs.yam.remote.proto import robot_env_pb2 as rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2

GRPC_GENERATED_VERSION = '1.80.0rc1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rlinf/envs/yam/remote/proto/robot_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotEnvServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpaces = channel.unary_unary(
                '/robot_env.RobotEnvService/GetSpaces',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.SpacesResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/robot_env.RobotEnvService/Reset',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ResetRequest.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Observation.FromString,
                _registered_method=True)
        self.ChunkStep = channel.unary_unary(
                '/robot_env.RobotEnvService/ChunkStep',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepRequest.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepResponse.FromString,
                _registered_method=True)
        self.SetTaskDescription = channel.unary_unary(
                '/robot_env.RobotEnvService/SetTaskDescription',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.TaskDescriptionRequest.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                _registered_method=True)
        self.EnterZeroTorqueMode = channel.unary_unary(
                '/robot_env.RobotEnvService/EnterZeroTorqueMode',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/robot_env.RobotEnvService/Close',
                request_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
                response_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                _registered_method=True)


class RobotEnvServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSpaces(self, request, context):
        """Return observation and action space metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the environment and return the initial observation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChunkStep(self, request, context):
        """Execute a chunk of actions and return per-step results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskDescription(self, request, context):
        """Update the task description string.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterZeroTorqueMode(self, request, context):
        """Switch the robot into zero-torque / zero-gravity mode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Close the environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotEnvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpaces,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.SpacesResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ResetRequest.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Observation.SerializeToString,
            ),
            'ChunkStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkStep,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepRequest.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepResponse.SerializeToString,
            ),
            'SetTaskDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTaskDescription,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.TaskDescriptionRequest.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            ),
            'EnterZeroTorqueMode': grpc.unary_unary_rpc_method_handler(
                    servicer.EnterZeroTorqueMode,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
                    response_serializer=rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_env.RobotEnvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_env.RobotEnvService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotEnvService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSpaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/GetSpaces',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.SpacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/Reset',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ResetRequest.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChunkStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/ChunkStep',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepRequest.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.ChunkStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTaskDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/SetTaskDescription',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.TaskDescriptionRequest.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnterZeroTorqueMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/EnterZeroTorqueMode',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_env.RobotEnvService/Close',
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.SerializeToString,
            rlinf_dot_envs_dot_yam_dot_remote_dot_proto_dot_robot__env__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
