name: Embodied End-to-End Tests

on:
  workflow_call:

jobs:
  embodied-mlp-sac-maniskill-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_sac_mlp
      
      - name: ManiSkill Async SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_sac_mlp_async

      - name: ManiSkill SAC Flow State test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_sac_flow_state

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
  
  embodied-cnn-realworld-dummy-sac-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill SAC test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh realworld_dummy_sac_cnn

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvla-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          bash requirements/install.sh embodied --model openvla --env maniskill_libero

      - name: ManiSkill PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh maniskill_ppo_openvla

      - name: ManiSkill Async PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run_async.sh maniskill_async_ppo_openvla

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          
  embodied-openvlaoft-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          bash requirements/install.sh embodied --model openvla-oft --env maniskill_libero

      - name: ManiSkill GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run.sh maniskill_grpo_openvlaoft

      - name: Libero-Goal GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_goal_grpo_openvlaoft

      - name: ManiSkill Async PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          cp -r /workspace/dataset/maniskill_assets/assets ${REPO_PATH}/rlinf/envs/maniskill/
          bash tests/e2e_tests/embodied/run_async.sh maniskill_async_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-behavior-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export BEHAVIOR_PATH=/workspace/dataset/BEHAVIOR-1K
          export ISAAC_SIM_WHEEL_PATH=/workspace/dataset/isaac_sim_wheels
          bash requirements/install.sh embodied --model openvla-oft --env behavior

      - name: BEHAVIOR-OpenVLA-OFT test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export OMNIGIBSON_DATA_PATH=/workspace/dataset/behavior-datasets
          export ISAAC_PATH=/workspace/dataset/isaac-sim
          bash tests/e2e_tests/embodied/run.sh behavior_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*
  
  embodied-openvlaoft-robotwin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla-oft --env robotwin

      - name: RoboTwin-OpenVLA-OFT test
        timeout-minutes: 30
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          export ROBOT_PLATFORM=ALOHA
          export ROBOTWIN_PATH="/workspace/dataset/RoboTwin"
          export PYTHONPATH=${ROBOTWIN_PATH}:$PYTHONPATH
          bash tests/e2e_tests/embodied/run.sh robotwin_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-gr00t-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T/
          bash requirements/install.sh embodied --model gr00t --env maniskill_libero

      - name: Libero-Spatial PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_gr00t

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
  
  embodied-gr00t-isaaclab-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export ISAAC_LAB_PATH=/workspace/dataset/IsaacLab
          export GR00T_PATH=/workspace/dataset/Isaac-GR00T/
          bash requirements/install.sh embodied --model gr00t --env isaaclab

      - name: ISAACLAB PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          source /workspace/dataset/isaac-sim-5.1/setup_conda_env.sh
          bash tests/e2e_tests/embodied/run.sh isaaclab_ppo_gr00t

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
          rm -rf /tmp/tmp*

  embodied-openvlaoft-metaworld-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          bash requirements/install.sh embodied --model openvla-oft --env metaworld

      - name: Metaworld PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh metaworld_50_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-calvin-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export CALVIN_PATH=/workspace/dataset/calvin
          bash requirements/install.sh embodied --model openvla-oft --env calvin

      - name: Calvin PPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh calvin_ppo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-dexbotic-maniskill-libero-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          export DEXBOTIC_PATH=/workspace/dataset/dexbotic
          bash requirements/install.sh embodied --model dexbotic --env maniskill_libero

      - name: Libero-Spatial PPO Dexbotic test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh libero_spatial_ppo_dexbotic_pi0

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-opensora-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          export OPENSORA_PATH=/workspace/dataset/opensora
          bash requirements/install.sh embodied --model openvla-oft --env opensora

      - name: OpenSora GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh opensora_libero_spatial_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  embodied-openvlaoft-wan-test:
    runs-on: embodied
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create embodied environment
        run: |
          unset UV_DEFAULT_INDEX
          export UV_PATH=/workspace/dataset/.uv
          export UV_LINK_MODE=symlink
          export UV_CACHE_DIR=/workspace/dataset/.uv_cache
          export UV_PYTHON_INSTALL_DIR=/workspace/dataset/.uv_python
          export LIBERO_PATH=/workspace/dataset/LIBERO
          export WAN_PATH=/workspace/dataset/wan
          bash requirements/install.sh embodied --model openvla-oft --env wan

      - name: Wan GRPO test
        timeout-minutes: 20
        run: |
          unset PYTHONPATH
          export REPO_PATH=$(pwd)
          source .venv/bin/activate
          bash tests/e2e_tests/embodied/run.sh wan_libero_spatial_grpo_openvlaoft

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune
